import{S as h,a as p,N as u}from"./assets/vendor-ef2f3eb2.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&o(l)}).observe(document,{childList:!0,subtree:!0});function c(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(e){if(e.ep)return;e.ep=!0;const r=c(e);fetch(e.href,r)}})();const y="45042225-41fd9f6f9757e1f3272f741dc",g="https://pixabay.com/api/",b=40;let n=1,d="",f=0,L=new h(".gallery a");const v=document.getElementById("search-form"),i=document.getElementById("gallery"),a=document.getElementById("load-more");v.addEventListener("submit",t=>{t.preventDefault(),d=t.target.elements.query.value.trim(),n=1,f=0,i.innerHTML="",a.classList.add("hidden"),m()});a.addEventListener("click",m);async function m(){if(d)try{const t=await p.get(g,{params:{key:y,q:d,image_type:"photo",orientation:"horizontal",safesearch:!0,page:n,per_page:b}});if(f=t.data.totalHits,t.data.hits.length===0&&n===1){u.Notify.failure("Sorry, there are no images matching your search query. Please try again!");return}E(t.data.hits),L.refresh(),n+=1,i.children.length<f?a.classList.remove("hidden"):(a.classList.add("hidden"),u.Notify.info("We're sorry, but you've reached the end of search results."))}catch(t){console.error("Error fetching images:",t)}}function E(t){const s=t.map(o=>`<a href="${o.largeImageURL}" class="gallery-item">
                    <img src="${o.webformatURL}" alt="${o.tags}" />
                    <div class="info">
                        <p><b>Likes</b>: ${o.likes}</p>
                        <p><b>Views</b>: ${o.views}</p>
                        <p><b>Comments</b>: ${o.comments}</p>
                        <p><b>Downloads</b>: ${o.downloads}</p>
                    </div>
                </a>`).join("");i.insertAdjacentHTML("beforeend",s);const{height:c}=i.firstElementChild.getBoundingClientRect();window.scrollBy({top:c*2,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
